services:
  auth-service:
    image: auth-service:latest
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
    environment:
      GATEWAYURL: http://api-gateway:8082
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://service-server:8081/eureka/
    restart: always
    ports:
      - "8072:8072"